// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteFile(arg1:string):Promise<void>;

export function GetCurrentUser():Promise<Record<string, string>>;

export function GetFilePreview(arg1:string):Promise<string>;

export function GetVaultPath():Promise<string>;

export function ListFiles():Promise<Array<main.FileRecord>>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenVaultFolder():Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetVaultPath(arg1:string):Promise<void>;

export function SignInWithGoogle():Promise<void>;

export function SignOut():Promise<void>;
