// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function GetFilePreview(arg1) {
  return window['go']['main']['App']['GetFilePreview'](arg1);
}

export function GetVaultPath() {
  return window['go']['main']['App']['GetVaultPath']();
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenVaultFolder() {
  return window['go']['main']['App']['OpenVaultFolder']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetVaultPath(arg1) {
  return window['go']['main']['App']['SetVaultPath'](arg1);
}
