// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatWithAgent'](arg1, arg2, arg3);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteFileEmbeddings(arg1) {
  return window['go']['main']['App']['DeleteFileEmbeddings'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetFilePreview(arg1) {
  return window['go']['main']['App']['GetFilePreview'](arg1);
}

export function GetIndexedFiles() {
  return window['go']['main']['App']['GetIndexedFiles']();
}

export function GetVaultPath() {
  return window['go']['main']['App']['GetVaultPath']();
}

export function IngestFile(arg1, arg2) {
  return window['go']['main']['App']['IngestFile'](arg1, arg2);
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function ListFolders() {
  return window['go']['main']['App']['ListFolders']();
}

export function MoveFileEmbeddings(arg1, arg2) {
  return window['go']['main']['App']['MoveFileEmbeddings'](arg1, arg2);
}

export function MoveFileToFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveFileToFolder'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenVaultFolder() {
  return window['go']['main']['App']['OpenVaultFolder']();
}

export function OrganiseFolder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OrganiseFolder'](arg1, arg2, arg3, arg4);
}

export function ParseOrganiseIntent(arg1) {
  return window['go']['main']['App']['ParseOrganiseIntent'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SemanticSearch(arg1, arg2) {
  return window['go']['main']['App']['SemanticSearch'](arg1, arg2);
}

export function SetVaultPath(arg1) {
  return window['go']['main']['App']['SetVaultPath'](arg1);
}

export function SignInWithGoogle() {
  return window['go']['main']['App']['SignInWithGoogle']();
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}
