// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChatWithAgent(arg1:string,arg2:Array<main.ChatMessage>,arg3:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteFileEmbeddings(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function GetCurrentUser():Promise<Record<string, string>>;

export function GetFilePreview(arg1:string):Promise<string>;

export function GetIndexedFiles():Promise<Record<string, boolean>>;

export function GetVaultPath():Promise<string>;

export function IngestFile(arg1:string,arg2:string):Promise<void>;

export function ListFiles():Promise<Array<main.FileRecord>>;

export function ListFolders():Promise<Array<main.FolderRecord>>;

export function MoveFileEmbeddings(arg1:string,arg2:string):Promise<void>;

export function MoveFileToFolder(arg1:string,arg2:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenVaultFolder():Promise<void>;

export function OrganiseFolder(arg1:string,arg2:string,arg3:string):Promise<main.OrganiseFolderResult>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function SemanticSearch(arg1:string,arg2:number):Promise<Array<main.SearchResult>>;

export function SetVaultPath(arg1:string):Promise<void>;

export function SignInWithGoogle():Promise<void>;

export function SignOut():Promise<void>;
